# Generated by Django 5.2.7 on 2025-11-07 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('fda_major_9', 'FDA Major 9'), ('dietary_preference', 'Dietary Preference'), ('custom', 'Custom User-Added')], default='custom', max_length=50)),
                ('alternative_names', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('usda_search_terms', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, default='Generic', max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('allergens', models.ManyToManyField(blank=True, related_name='ingredients', to='Buddy_Crocker.allergen')),
            ],
            options={
                'ordering': ['name', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='pantries', to='Buddy_Crocker.ingredient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pantries',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergens', models.ManyToManyField(blank=True, related_name='profiles', to='Buddy_Crocker.allergen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='recipes', to='Buddy_Crocker.ingredient')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name', 'brand'], name='Buddy_Crock_name_18acb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'brand')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('title', 'author')},
        ),
    ]
