# Generated by Django 5.2.7 on 2025-11-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_crocker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='allergen',
            name='category',
            field=models.CharField(choices=[('fda_major_9', 'FDA Major 9'), ('dietary_preference', 'Dietary Preference'), ('custom', 'Custom User-Added')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='allergen',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allergen',
            name='usda_search_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergens',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='buddy_crocker.allergen'),
        ),
    ]
