# Generated by Django 5.2.7 on 2025-10-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buddy_Crocker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='allergens',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
