# Generated by Django 5.2.8 on 2025-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_crocker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fdc_id',
            field=models.PositiveIntegerField(blank=True, help_text='USDA FoodData Central ID', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='When nutrition/portion data was last updated'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete nutrient data from USDA (macros, vitamins, minerals)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='portion_data',
            field=models.JSONField(blank=True, default=list, help_text='Available serving sizes with gram weights from USDA'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.PositiveIntegerField(help_text='Calories per 100g (USDA standard)'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['fdc_id'], name='buddy_crock_fdc_id_c8bbcc_idx'),
        ),
    ]
