# Generated by Django 5.2.7 on 2025-11-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buddy_Crocker', '0002_allergen_alternative_names_allergen_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name', 'brand']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(blank=True, default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'brand')},
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name', 'brand'], name='Buddy_Crock_name_18acb7_idx'),
        ),
    ]
