# Generated by Django 5.2.7 on 2025-10-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buddy_Crocker', '0002_remove_ingredient_allergens_ingredient_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='Buddy_Crocker.ingredient'),
        ),
    ]
