# Generated by Django 5.2.8 on 2025-12-05 04:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_crocker', '0002_ingredient_fdc_id_ingredient_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, help_text='Cooking time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Recipe difficulty level', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the finished dish', null=True, upload_to='recipe_images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='placeholder_color',
            field=models.CharField(default='#0B63F2', help_text='Hex color for placeholder card', max_length=7),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4, help_text='Number of servings this recipe makes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount of ingredient (e.g., 2 for '2 cups')", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., cup, tsp, g, oz)', max_length=50)),
                ('gram_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams for calorie calculation', max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, help_text="Optional notes (e.g., 'chopped', 'to taste')", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of ingredient in recipe')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='buddy_crocker.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='buddy_crocker.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
