# Generated by Django 5.2.7 on 2025-11-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_crocker', '0003_alter_ingredient_options_ingredient_brand_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingredient',
            new_name='buddy_crock_name_ad7877_idx',
            old_name='Buddy_Crock_name_18acb7_idx',
        ),
    ]
