# Generated by Django 5.2.8 on 2025-12-05 04:12

from django.db import migrations


def convert_to_through_model(apps, schema_editor):
    Recipe = apps.get_model('buddy_crocker', 'Recipe')
    RecipeIngredient = apps.get_model('buddy_crocker', 'RecipeIngredient')
    
    for recipe in Recipe.objects.all():
        for i, ingredient in enumerate(recipe.ingredients.all()):
            RecipeIngredient.objects.get_or_create(
                recipe=recipe, ingredient=ingredient,
                defaults={'amount': 1, 'unit': 'serving', 'order': i}
            )

class Migration(migrations.Migration):
    dependencies = [('buddy_crocker', '0003_add_recipeingredient')]  # Your new migration
    operations = [migrations.RunPython(convert_to_through_model, migrations.RunPython.noop)]