# Generated by Django 5.2.7 on 2025-11-14 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buddy_Crocker', '0003_alter_ingredient_options_ingredient_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
