# Generated by Django 5.2.7 on 2025-11-16 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_crocker', '0003_alter_ingredient_options_ingredient_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='ingredient',
            new_name='buddy_crock_name_ad7877_idx',
            old_name='Buddy_Crock_name_18acb7_idx',
        ),
        migrations.AddField(
            model_name='scanratelimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scanratelimit',
            index=models.Index(fields=['user', '-timestamp'], name='buddy_crock_user_id_ee149f_idx'),
        ),
    ]
