# Generated by Django 5.2.8 on 2025-12-05 04:19

from django.db import migrations


def populate_recipeingredients(apps, schema_editor):
    Recipe = apps.get_model('buddy_crocker', 'Recipe')
    RecipeIngredient = apps.get_model('buddy_crocker', 'RecipeIngredient')
    
    for recipe in Recipe.objects.all():
        for i, ingredient in enumerate(recipe.ingredients.all()):
            RecipeIngredient.objects.get_or_create(
                recipe=recipe,
                ingredient=ingredient,
                defaults={
                    'amount': 1.0,
                    'unit': 'serving', 
                    'order': i,
                    'gram_weight': None,
                    'notes': ''
                }
            )

class Migration(migrations.Migration):
    dependencies = [('buddy_crocker', '0004_auto_20251205_0412')]
    
    operations = [
        migrations.RunPython(populate_recipeingredients, migrations.RunPython.noop),
    ]