# Generated by Django 5.2.7 on 2025-11-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buddy_Crocker', '0003_alter_ingredient_options_ingredient_brand_and_more'),
        ('Buddy_Crocker', '0004_change_recipe_ingredients_to_text'),
    ]

    operations = [
    ]
