# Generated by Django 5.2.7 on 2025-12-09 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_crocker', '0005_populate_recipeingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(help_text='Name of ingredient or item to purchase', max_length=200)),
                ('quantity', models.CharField(blank=True, default='', help_text="Amount needed (e.g., '2 cups', '500g')", max_length=100)),
                ('is_purchased', models.BooleanField(default=False, help_text='Whether this item has been purchased')),
                ('notes', models.CharField(blank=True, default='', help_text="Additional notes (e.g., 'organic', 'brand preference')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_from_recipe', models.ForeignKey(blank=True, help_text='Recipe this ingredient was added from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='buddy_crocker.recipe')),
                ('ingredient', models.ForeignKey(blank=True, help_text='Link to ingredient in database if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='buddy_crocker.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_purchased', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_purchased'], name='buddy_crock_user_id_877fe7_idx'), models.Index(fields=['user', '-created_at'], name='buddy_crock_user_id_15af7b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'ingredient_name'), name='unique_user_ingredient_name')],
            },
        ),
    ]
