name: Run Tests with Coverage

on:
  push:
    branches: ['**']  # Run on all branches
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      SECRET_KEY: 'test-secret-key-for-github-actions'
      ENVIRONMENT: 'development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Match your Python version
      
      - name: Install dependencies
        working-directory: ./Buddy_Crocker
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run migrations
        working-directory: ./Buddy_Crocker
        run: |
          python manage.py migrate
        env:
      
      - name: Run tests with coverage
        working-directory: ./Buddy_Crocker
        run: |
          coverage run --source='.' manage.py test
          echo "=========================================="
          echo "TEST COVERAGE REPORT"
          echo "=========================================="
          coverage report -m
          echo "=========================================="
      
